#!/usr/bin/env bash
# A script To create the file /var/run/holbertonscript.pid that contain its PID
# To display "To infinity and beyond" indefinitely
# To display "I hate the kill command" when receiving a SIGTERM signal
# To display "Y U no love me?!" when receiving a SIGINT signal
# To delete the file /var/run/holbertonscript.pid

caza()
{
	rm /var/run/holbertonscript.pid
	i=2
}
echo $$ > /var/run/holbertonscript.pid
i=0
while [ $i -le 1 ]
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' 15
	trap 'echo "Y U no love me?!"' 2
	trap caza 3 15
done
