#!/usr/bin/env bash
# To create the file /var/run/holbertonscript.pid that contain its PID
# To display "To infinity and beyond" indefinitely
# To display "I hate the kill command" when receiving a SIGTERM signal
# To display "Y U no love me?!" when receiving a SIGINT signal
# To delete the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
while true; do
      echo "To infinity and beyond"
      sleep 2
done
